print("=====STUDENT DETAILS=====")
name=input("Enter your Name:")
age=int(input("Enter your Age:"))
college=input("Enter your College:")
department=input("Enter your Department:")
print("\n STUDENT DETAILS")
print("Name:",name)
print("Age:",age)
print("College:",college)
print("Department:",department)
print("\n CALCULATOR" )
num1=float(input("Enter your first number"))
num2=float(input("Enter your second number"))
print("\n results")      
print("Addition:",num1+num2)
print("subtraction:",num1-num2)
print("mutiplication:",num1*num2)
print("division:",num1/num2)
print("modulus:",num1%num2)
print("\n DATA TYPES")
print(type(name))
print(type(age))
print(type(college))
print(type(department))


